remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: [Predicting Power Outage Durations]
description: [This data science project aims to predict the duration of power outages in the United States. This project was completed in the DSC80 course at UCSD alongside Adam Walters.]